In [ ]:
# conect drive to colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# data upload
import pandas as pd
df=pd.read_csv('/content/household_power_consumption.txt')

In [ ]:
#head() represents the 5 row
df.head()

  Date;Time;Global_active_power;Global_reactive_power;Voltage;Global_intensity;Sub_metering_1;Sub_metering_2;Sub_metering_3
0  16/12/2006;17:24:00;4.216;0.418;234.840;18.400...
1  16/12/2006;17:25:00;5.360;0.436;233.630;23.000...
2  16/12/2006;17:26:00;5.374;0.498;233.290;23.000...
3  16/12/2006;17:27:00;5.388;0.502;233.740;23.000...
4  16/12/2006;17:28:00;3.666;0.528;235.680;15.800...

In [ ]:
#tail() represents the last 5 rows
df.tail()

        Date;Time;Global_active_power;Global_reactive_power;Voltage;Global_intensity;Sub_metering_1;Sub_metering_2;Sub_metering_3
1517385  4/11/2009;11:09:00;0.432;0.168;241.250;2.000;1...
1517386  4/11/2009;11:10:00;0.426;0.160;241.150;1.800;1...
1517387  4/11/2009;11:11:00;0.420;0.158;241.650;1.800;1...
1517388  4/11/2009;11:12:00;0.454;0.140;241.200;2.000;1...
1517389  4/11/2009;11:13:00;0.460;0.138;241.770;2.000;1...

In [ ]:
df.info()#use to know the information of the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1517390 entries, 0 to 1517389
Data columns (total 1 columns):
 #   Column                                                                                                                     Non-Null Count    Dtype
---  ------                                                                                                                     --------------    -----
 0   Date;Time;Global_active_power;Global_reactive_power;Voltage;Global_intensity;Sub_metering_1;Sub_metering_2;Sub_metering_3  1517390 non-null  object
dtypes: object(1)
memory usage: 11.6+ MB

In [ ]:
df.describe()#describe the data

       Date;Time;Global_active_power;Global_reactive_power;Voltage;Global_intensity;Sub_metering_1;Sub_metering_2;Sub_metering_3
count                                             1517390
unique                                            1517390
top     4/11/2009;11:13:00;0.460;0.138;241.770;2.000;1...
freq                                                    1

In [ ]:
df.isnull()#use to find missing values,false indicates noo missing value ,true indicates missing value

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19730,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19731,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19732,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19733,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19734,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.duplicated()# use to find duplicate values

0        False
1        False
2        False
3        False
4        False
         ...
19730    False
19731    False
19732    False
19733    False
19734    False
Length: 19735, dtype: bool

In [ ]:
df.shape#use to know the rows and cols

(19735, 29)

In [ ]:
X = df.drop(["Appliances", "date"], axis=1)#x=train
y = df["Appliances"]#y=output

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score :", r2_score(y_test, y_pred))

MAE : 32.60259690904485
RMSE : 68.04007425377402
R2 Score : 0.5373828757084171

In [ ]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor
from xgboost import XGBRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Extra Trees": ExtraTreesRegressor(n_estimators=100, random_state=42),
    "XGBoost": XGBRegressor(random_state=42)
}

In [ ]:
results = []

for name, model in models.items():

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Metrics
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    results.append({
        "Model": name,
        "MAE": round(mae,2),
        "MSE": round(mse,2),
        "RMSE": round(rmse,2),
        "R2 Score": round(r2,4)
    })

In [ ]:
results_df = pd.DataFrame(results)

results_df.sort_values(by="R2 Score", ascending=False)

               Model    MAE      MSE   RMSE  R2 Score
3        Extra Trees  29.71  4072.93  63.82    0.5930
2      Random Forest  32.90  4680.95  68.42    0.5322
4            XGBoost  36.33  5104.44  71.45    0.4899
1      Decision Tree  38.87  8207.73  90.60    0.1798
0  Linear Regression  52.55  8312.85  91.17    0.1693

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor

final_model = ExtraTreesRegressor(
    n_estimators=200,
    random_state=42
)

final_model.fit(X_train, y_train)

ExtraTreesRegressor(n_estimators=200, random_state=42)

In [ ]:
import joblib

joblib.dump(final_model, "electricity_model.pkl")

print("Model Saved Successfully")

Model Saved Successfully

In [ ]:
from google.colab import files

files.download("electricity_model.pkl")